import { BudgetProfile, ExpenseRecord, InvestmentHolding } from './types';

export const DEFAULT_BUDGET_PROFILE: Omit<BudgetProfile, 'userId'> = {
  monthlyAllowance: 1450,
  savingsBalance: 185.5,
  alertThresholdPercent: 80,
  foodLimit: 380,
  housingLimit: 240,
  transitLimit: 110,
  subscriptionsLimit: 65,
  socialLimit: 160,
  essentialsLimit: 195,
};

export const INITIAL_DEMO_EXPENSES: Omit<ExpenseRecord, 'userId'>[] = [
  {
    id: 'demo_exp_1',
    title: 'Campus Union Espresso & Panini',
    category: 'Coffee & Social',
    amount: 14.25,
    dateStr: '2026-10-01',
    paymentMethod: 'Campus Card',
    isRecurring: false,
    roundUpSaved: 0.75,
  },
  {
    id: 'demo_exp_2',
    title: 'Organic Chemistry Lab Manual & Access Code',
    category: 'Textbooks & Academic',
    amount: 168.0,
    dateStr: '2026-10-01',
    paymentMethod: 'Debit Card',
    isRecurring: false,
    roundUpSaved: 1.0,
  },
  {
    id: 'demo_exp_3',
    title: 'Late-Night Delivery — ThaiNoodle Express',
    category: 'Food & Dining',
    amount: 34.4,
    dateStr: '2026-09-29',
    paymentMethod: 'UPI / Wallet',
    isRecurring: false,
    roundUpSaved: 0.6,
  },
  {
    id: 'demo_exp_4',
    title: 'Trader Joe’s Weekly Dorm Groceries',
    category: 'Food & Dining',
    amount: 142.15,
    dateStr: '2026-09-27',
    paymentMethod: 'Debit Card',
    isRecurring: false,
    roundUpSaved: 0.85,
  },
  {
    id: 'demo_exp_5',
    title: 'Streaming Bundle + Cloud Storage Pro',
    category: 'Subscriptions & Apps',
    amount: 29.99,
    dateStr: '2026-09-25',
    paymentMethod: 'Debit Card',
    isRecurring: true,
    roundUpSaved: 0.01,
  },
  {
    id: 'demo_exp_6',
    title: 'AI Study Research Copilot Subscription',
    category: 'Subscriptions & Apps',
    amount: 24.0,
    dateStr: '2026-09-24',
    paymentMethod: 'Debit Card',
    isRecurring: true,
    roundUpSaved: 1.0,
  },
  {
    id: 'demo_exp_7',
    title: 'Metro U-Pass Reload & Scooter Rides',
    category: 'Campus Transit',
    amount: 78.5,
    dateStr: '2026-09-22',
    paymentMethod: 'UPI / Wallet',
    isRecurring: true,
    roundUpSaved: 0.5,
  },
  {
    id: 'demo_exp_8',
    title: 'Specialty Cold Brew & Weekend Brunch',
    category: 'Coffee & Social',
    amount: 126.8,
    dateStr: '2026-09-20',
    paymentMethod: 'Debit Card',
    isRecurring: false,
    roundUpSaved: 0.2,
  },
  {
    id: 'demo_exp_9',
    title: 'Campus Grill & Burrito Bowl',
    category: 'Food & Dining',
    amount: 158.6,
    dateStr: '2026-09-18',
    paymentMethod: 'Campus Card',
    isRecurring: false,
    roundUpSaved: 0.4,
  },
  {
    id: 'demo_exp_10',
    title: 'Dorm Laundry Credits & Household Supplies',
    category: 'Dorm & Essentials',
    amount: 94.3,
    dateStr: '2026-09-15',
    paymentMethod: 'Campus Card',
    isRecurring: false,
    roundUpSaved: 0.7,
  },
];

export const INITIAL_DEMO_INVESTMENTS: Omit<InvestmentHolding, 'userId'>[] = [
  {
    id: 'demo_inv_1',
    assetClass: 'Low-Risk Savings',
    instrumentName: 'Campus High-Yield Savings Vault',
    investedAmount: 420,
    unitsOwned: 420,
    expectedApy: 4.85,
    riskTier: 'Low',
    autoInvestMonthly: 50,
  },
  {
    id: 'demo_inv_2',
    assetClass: 'Automated Index Funds',
    instrumentName: 'Vanguard S&P 500 Fractional ETF (VOO)',
    investedAmount: 560,
    unitsOwned: 1.0929,
    expectedApy: 10.4,
    riskTier: 'Moderate',
    autoInvestMonthly: 75,
  },
  {
    id: 'demo_inv_3',
    assetClass: 'Crypto',
    instrumentName: 'Blue-Chip Crypto Basket (70% BTC / 30% ETH)',
    investedAmount: 195,
    unitsOwned: 0.78,
    expectedApy: 18.5,
    riskTier: 'High',
    autoInvestMonthly: 20,
  },
  {
    id: 'demo_inv_4',
    assetClass: 'P2P Lending',
    instrumentName: 'Verified Campus Peer Micro-Credit Pool',
    investedAmount: 250,
    unitsOwned: 10.0,
    expectedApy: 11.2,
    riskTier: 'Moderate',
    autoInvestMonthly: 25,
  },
  {
    id: 'demo_inv_5',
    assetClass: 'Digital Gold & Silver',
    instrumentName: '24K 99.99% Swiss Vaulted Digital Gold',
    investedAmount: 215,
    unitsOwned: 2.4855,
    expectedApy: 9.2,
    riskTier: 'Precious Metal',
    autoInvestMonthly: 25,
  },
  {
    id: 'demo_inv_6',
    assetClass: 'Digital Gold & Silver',
    instrumentName: '99.9% Fine Industrial Digital Silver',
    investedAmount: 110,
    unitsOwned: 3.4591,
    expectedApy: 8.7,
    riskTier: 'Precious Metal',
    autoInvestMonthly: 15,
  },
];
